### ISSUE TITLE
Remove color field on apps

### ISSUE THREAD

**Issue by mjlescano** [DemocraciaEnRed/civicstack#37]
This Color Picker:
![image](https://cloud.githubusercontent.com/assets/558901/16383408/63ad2cac-3c5b-11e6-90c7-d132d1152434.png)

We only ask for it to put a background on the image. Instead, the image should be `background-size: cover;`

**Comment by jfresco** [comment]
I think I'm not getting it.
It is a fact that we are using the `backgroundColor` property to put it as a background color for the logo. But if we remove it, the logo background will be white, and I don't get how putting the logo as `background-size: cover;` will improve it.

For example, if we apply that styles to this:
![image](https://cloud.githubusercontent.com/assets/4335188/16973364/74c088b2-4e09-11e6-8a00-45db2e3bfa65.png)

it will become this:
![image](https://cloud.githubusercontent.com/assets/4335188/16973382/91e7b3fc-4e09-11e6-9465-d920be521acb.png)

Can you send me some mockups in order to get what is the visual improvement you want to achieve?

**Comment by mjlescano** [comment]
What about using `background-size: contain` + [`corner-colors`](https://github.com/JuhQ/corner-colors) for `background-color` ?

**Comment by mjlescano** [comment]
or simply `background-size: contain` + `background-color: #333`

**Comment by mjlescano** [comment]
buuuut, what about when is a `.png` with transparent background? :/

**Comment by jfresco** [comment]
Don't know. Please send me some mockups or example (perhaps editing the DOM directly from DevTools with the changes you want) so I can understand what you want to achieve.

**Comment by mjlescano** [comment]
We're closing this until there's a better solution
